version: '3'

services:
  db:
    image: mysql:5.7.20
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: config/docker/web/prod/Dockerfile
    volumes:
      - ./config/docker/web/prod/php.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - ./config/docker/web/.bash_history:/root/.bash_history
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    volumes:
      - ./config/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file: .env
    depends_on:
      - web

volumes:
  mysql-data: